# Generated by Django 5.1 on 2024-09-07 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_collector', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='childmortality',
            name='mortality_rate',
        ),
        migrations.RemoveField(
            model_name='childmortality',
            name='year',
        ),
        migrations.AddField(
            model_name='childmortality',
            name='cause_of_death',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='childmortality',
            name='child_age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='childmortality',
            name='child_gender',
            field=models.CharField(default='Unknown', max_length=10),
        ),
        migrations.AddField(
            model_name='childmortality',
            name='facility_capacity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='childmortality',
            name='facility_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='childmortality',
            name='facility_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='childmortality',
            name='gdp',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='childmortality',
            name='population',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='childmortality',
            name='region_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
